{% macro monad_vars() %}
    {% set vars = {
        'GLOBAL_PROJECT_NAME': 'monad',
        'GLOBAL_NODE_PROVIDER': 'quicknode',
        'GLOBAL_NODE_URL': "{URL}",
        'GLOBAL_NODE_VAULT_PATH': 'Vault/prod/evm/quicknode/monad/mainnet',
        'GLOBAL_WRAPPED_NATIVE_ASSET_SYMBOL': 'WMON',
        'GLOBAL_NATIVE_ASSET_SYMBOL': 'MON',
        'MAIN_SL_BLOCKS_PER_HOUR': 10000,
        'MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_SQL_LIMIT': 1000000,
        'MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_PRODUCER_BATCH_SIZE': 10000,
        'MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_WORKER_BATCH_SIZE': 1000,
        'MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_ASYNC_CONCURRENT_REQUESTS': 10,
        'MAIN_SL_RECEIPTS_HISTORY_SQL_LIMIT': 1000000,
        'MAIN_SL_RECEIPTS_HISTORY_PRODUCER_BATCH_SIZE': 10000,
        'MAIN_SL_RECEIPTS_HISTORY_WORKER_BATCH_SIZE': 1000,
        'MAIN_SL_RECEIPTS_HISTORY_ASYNC_CONCURRENT_REQUESTS': 10,
        'MAIN_SL_TRACES_HISTORY_SQL_LIMIT': 1000000,
        'MAIN_SL_TRACES_HISTORY_PRODUCER_BATCH_SIZE': 10000,
        'MAIN_SL_TRACES_HISTORY_WORKER_BATCH_SIZE': 1000,
        'MAIN_SL_TRACES_HISTORY_ASYNC_CONCURRENT_REQUESTS': 10,
        'MAIN_PRICES_NATIVE_SYMBOLS': 'MON',
        'MAIN_PRICES_NATIVE_BLOCKCHAINS': 'monad',
        'MAIN_PRICES_PROVIDER_PLATFORMS': 'monad',
        'MAIN_GHA_STREAMLINE_CHAINHEAD_CRON': '24,54 * * * *',
        'MAIN_GHA_SCHEDULED_SCORES_CRON': '45 5 * * *'
    } %}
    
    {{ return(vars) }}

{% endmacro %} 