# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'fsc_evm'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fsc_evm'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  fsc_evm:
    +enabled: false
    +pre-hook: "{{ log_model_details() }}"
    main_package:
      +on-run-start: "{{ return_vars() }}"
      variables:
        +enabled: true
      core:
        +enabled: true

vars:
  "dbt_date:time_zone": GMT
  
  # Global Variables
  "GLOBAL_PROD_DB_NAME": "example_db"
  "GLOBAL_CHAIN_NETWORK": "mainnet"
  "GLOBAL_NODE_URL": "{URL}"
  "GLOBAL_NODE_PROVIDER": "example_provider"
  "GLOBAL_WRAPPED_NATIVE_ASSET_ADDRESS": "0x0000000000000000000000000000000000000000"
  
  # Streamline Variables
  "MAIN_SL_BLOCKS_PER_HOUR": 240
  "MAIN_SL_TRANSACTIONS_PER_BLOCK": 100
  "MAIN_SL_CHAINHEAD_DELAY_MINUTES": 3
  
  # Feature Flags
  "MAIN_CORE_RECEIPTS_BY_HASH_ENABLED": false
  "MAIN_SL_NEW_BUILD_ENABLED": false