# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'fsc_evm'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fsc_evm'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

vars:
  "dbt_date:time_zone": GMT
  STREAMLINE_INVOKE_STREAMS: False
  STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES: False

  ### GLOBAL VARIABLES
  GLOBAL_PROD_DB_NAME: '' ### REQUIRED
  GLOBAL_NODE_SECRET_PATH: '' ### REQUIRED
  GLOBAL_BLOCKS_PER_HOUR: 0 ### REQUIRED

  ### PRICES ###
  PRICES_SYMBOLS: '' ### REQUIRED 
  PRICES_PLATFORMS: [] ### REQUIRED
  PRICES_TOKEN_ADDRESSES: [] ### OPTIONAL
  PRICES_BLOCKCHAINS: '' ### OPTIONAL (Default: GLOBAL_PROD_DB_NAME)

  ### LABELS ###
  LABELS_BLOCKCHAINS: '' ### OPTIONAL (Default: GLOBAL_PROD_DB_NAME)

  ### STATS ###
  STATS_TOKEN_ADDRESS: '' ### REQUIRED

  ### BRONZE ###
  BRONZE_BLOCKS_SOURCE_VERSION: '' ### OPTIONAL
  BRONZE_TRANSACTIONS_SOURCE_VERSION: '' ### OPTIONAL
  BRONZE_RECEIPTS_SOURCE_VERSION: '' ### OPTIONAL
  BRONZE_RECEIPTS_BY_HASH_SOURCE_VERSION: '' ### OPTIONAL
  BRONZE_TRACES_SOURCE_VERSION: '' ### OPTIONAL
  BRONZE_CONFIRM_BLOCKS_SOURCE_VERSION: '' ### OPTIONAL

  BRONZE_ETH_BALANCES_SOURCE_VERSION: '' ### OPTIONAL
  BRONZE_TOKEN_BALANCES_SOURCE_VERSION: '' ### OPTIONAL

  BRONZE_CONTRACT_ABIS_SOURCE_VERSION: '' ### OPTIONAL

  BRONZE_BEACON_BLOCKS_SOURCE_VERSION: '' ### OPTIONAL
  BRONZE_BEACON_VALIDATORS_SOURCE_VERSION: '' ### OPTIONAL

  BRONZE_DECODED_LOGS_SOURCE_VERSION: '' ### OPTIONAL
  BRONZE_DECODED_TRACES_SOURCE_VERSION: '' ### OPTIONAL

  BRONZE_READS_SOURCE_VERSION: '' ### OPTIONAL
