{% macro return_vars() %}
  {# This macro sets and returns all configurable variables used throughout the project,
     organizing them by category (Global, Bronze, Silver, Streamline, Decoder etc.) with default values.
     IMPORTANT: Only call get_var() once per variable #}
  
  {# Set all variables on the namespace #}
  {% set ns = namespace() %}
  
  {# Set Variables and Default Values, organized by category #}
  
  {# Global Variables #}
  {% set ns.GLOBAL_PROJECT_NAME = get_var('GLOBAL_PROJECT_NAME', '') %}
  {% set ns.GLOBAL_NODE_PROVIDER = get_var('GLOBAL_NODE_PROVIDER', '') %}
  {% set ns.GLOBAL_NODE_URL = get_var('GLOBAL_NODE_URL', '{Service}/{Authentication}') %}
  {% set ns.GLOBAL_NATIVE_ASSET_SYMBOL = get_var('GLOBAL_NATIVE_ASSET_SYMBOL', '') %}
  {% set ns.GLOBAL_WRAPPED_NATIVE_ASSET_ADDRESS = get_var('GLOBAL_WRAPPED_NATIVE_ASSET_ADDRESS', '') %}
  {% set ns.GLOBAL_WRAPPED_NATIVE_ASSET_SYMBOL = get_var('GLOBAL_WRAPPED_NATIVE_ASSET_SYMBOL', '') %}
  {% set ns.GLOBAL_MAX_SEQUENCE_NUMBER = get_var('GLOBAL_MAX_SEQUENCE_NUMBER', 1000000000) %}
  {% set ns.GLOBAL_NODE_VAULT_PATH = get_var('GLOBAL_NODE_VAULT_PATH', '') %}
  {% set ns.GLOBAL_NETWORK = get_var('GLOBAL_NETWORK', 'mainnet') %}
  {% set ns.GLOBAL_START_BLOCK = get_var('GLOBAL_START_BLOCK', 0) %}

  {% set ns.GLOBAL_BRONZE_FR_ENABLED = none if get_var('GLOBAL_BRONZE_FR_ENABLED', false) else false %} {# Sets to none if true, still requires --full-refresh, otherwise will use incremental #}
  {% set ns.GLOBAL_SILVER_FR_ENABLED = none if get_var('GLOBAL_SILVER_FR_ENABLED', false) else false %} 
  {% set ns.GLOBAL_GOLD_FR_ENABLED = none if get_var('GLOBAL_GOLD_FR_ENABLED', false) else false %} 
  {% set ns.GLOBAL_STREAMLINE_FR_ENABLED = none if get_var('GLOBAL_STREAMLINE_FR_ENABLED', false) else false %} 
  {% set ns.GLOBAL_NEW_BUILD_ENABLED = get_var('GLOBAL_NEW_BUILD_ENABLED', false) %}

  {% set ns.GLOBAL_CHANGE_TRACKING_ENABLED = get_var('GLOBAL_CHANGE_TRACKING_ENABLED', false) %}
  
  {# Main GHA Workflow Variables #}
  {% set ns.MAIN_GHA_STREAMLINE_CHAINHEAD_CRON = get_var('MAIN_GHA_STREAMLINE_CHAINHEAD_CRON', '0,30 * * * *') %}
  {% set ns.MAIN_GHA_SCHEDULED_MAIN_CRON = get_var('MAIN_GHA_SCHEDULED_MAIN_CRON', none) %}
  {% set ns.MAIN_GHA_SCHEDULED_CURATED_CRON = get_var('MAIN_GHA_SCHEDULED_CURATED_CRON', none) %}
  {% set ns.MAIN_GHA_SCHEDULED_ABIS_CRON = get_var('MAIN_GHA_SCHEDULED_ABIS_CRON', none) %}
  {% set ns.MAIN_GHA_SCHEDULED_SCORES_CRON = get_var('MAIN_GHA_SCHEDULED_SCORES_CRON', none) %}
  {% set ns.MAIN_GHA_TEST_DAILY_CRON = get_var('MAIN_GHA_TEST_DAILY_CRON', none) %}
  {% set ns.MAIN_GHA_TEST_INTRADAY_CRON = get_var('MAIN_GHA_TEST_INTRADAY_CRON', none) %}
  {% set ns.MAIN_GHA_TEST_MONTHLY_CRON = get_var('MAIN_GHA_TEST_MONTHLY_CRON', none) %}
  {% set ns.MAIN_GHA_HEAL_MODELS_CRON = get_var('MAIN_GHA_HEAL_MODELS_CRON', none) %}
  {% set ns.MAIN_GHA_FULL_OBSERVABILITY_CRON = get_var('MAIN_GHA_FULL_OBSERVABILITY_CRON', none) %}
  {% set ns.MAIN_GHA_DEV_REFRESH_CRON = get_var('MAIN_GHA_DEV_REFRESH_CRON', none) %}
  {% set ns.MAIN_GHA_STREAMLINE_DECODER_HISTORY_CRON = get_var('MAIN_GHA_STREAMLINE_DECODER_HISTORY_CRON', none) %}

  {# Custom GHA Workflow Variables #}
  {% set ns.CUSTOM_GHA_STREAMLINE_DEXALOT_CHAINHEAD_CRON = get_var('CUSTOM_GHA_STREAMLINE_DEXALOT_CHAINHEAD_CRON', none) %}
  {% set ns.CUSTOM_GHA_SCHEDULED_DEXALOT_MAIN_CRON = get_var('CUSTOM_GHA_SCHEDULED_DEXALOT_MAIN_CRON', none) %}
  {% set ns.CUSTOM_GHA_TEST_BEACON_CRON = get_var('CUSTOM_GHA_TEST_BEACON_CRON', none) %}
  {% set ns.CUSTOM_GHA_STREAMLINE_READS_CRON = get_var('CUSTOM_GHA_STREAMLINE_READS_CRON', none) %}
  {% set ns.CUSTOM_GHA_STREAMLINE_BEACON_CRON = get_var('CUSTOM_GHA_STREAMLINE_BEACON_CRON', none) %}
  {% set ns.CUSTOM_GHA_SCHEDULED_BEACON_CRON = get_var('CUSTOM_GHA_SCHEDULED_BEACON_CRON', none) %}
  {% set ns.CUSTOM_GHA_NFT_READS_CRON = get_var('CUSTOM_GHA_NFT_READS_CRON', none) %}
  {% set ns.CUSTOM_GHA_NFT_LIST_CRON = get_var('CUSTOM_GHA_NFT_LIST_CRON', none) %}

  {# Core Variables #}
  {% set ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED = get_var('MAIN_CORE_RECEIPTS_BY_HASH_ENABLED', false) %}

  {% set ns.MAIN_CORE_TRACES_ARB_MODE = ns.GLOBAL_PROJECT_NAME.upper() == 'ARBITRUM' %}
  {% set ns.MAIN_CORE_TRACES_SEI_MODE = ns.GLOBAL_PROJECT_NAME.upper() == 'SEI' %}
  {% set ns.MAIN_CORE_TRACES_KAIA_MODE = ns.GLOBAL_PROJECT_NAME.upper() == 'KAIA' %}

  {# Core Bronze Variables #}
  {% set ns.MAIN_CORE_BRONZE_BLOCKS_ERROR_CODE_ENABLED = get_var('MAIN_CORE_BRONZE_BLOCKS_ERROR_CODE_ENABLED', false) %}
  {% set ns.MAIN_CORE_BRONZE_TOKEN_READS_LIMIT = get_var('MAIN_CORE_BRONZE_TOKEN_READS_LIMIT', 50) %}
  {% set ns.MAIN_CORE_BRONZE_TOKEN_READS_BATCHED_ENABLED = get_var('MAIN_CORE_BRONZE_TOKEN_READS_BATCHED_ENABLED', false) %}

  {# Core Silver Variables #}
  {% set ns.MAIN_CORE_SILVER_RECEIPTS_UNIQUE_KEY = 'tx_hash' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'block_number' %}
  {% set ns.MAIN_CORE_SILVER_RECEIPTS_SOURCE_NAME = 'RECEIPTS_BY_HASH' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'RECEIPTS' %}
  {% set ns.MAIN_CORE_SILVER_RECEIPTS_POST_HOOK = "ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION on equality(tx_hash, block_number)" if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else "ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION on equality(array_index, block_number)" %}

  {% set ns.MAIN_CORE_SILVER_CONFIRM_BLOCKS_FULL_RELOAD_ENABLED = get_var('MAIN_CORE_SILVER_CONFIRM_BLOCKS_FULL_RELOAD_ENABLED', false) %}

  {% set ns.MAIN_CORE_SILVER_TRACES_FULL_RELOAD_ENABLED = get_var('MAIN_CORE_SILVER_TRACES_FULL_RELOAD_ENABLED', false) %}
  {% set ns.MAIN_CORE_SILVER_TRACES_FR_MAX_BLOCK = get_var('MAIN_CORE_SILVER_TRACES_FR_MAX_BLOCK', 1000000) %}
  {% set ns.MAIN_CORE_SILVER_TRACES_FULL_RELOAD_BLOCKS_PER_RUN = get_var('MAIN_CORE_SILVER_TRACES_FULL_RELOAD_BLOCKS_PER_RUN', 1000000) %}
  {% set ns.MAIN_CORE_SILVER_TRACES_PARTITION_KEY_ENABLED = get_var('MAIN_CORE_SILVER_TRACES_PARTITION_KEY_ENABLED', true) %}

  {# Core Gold Variables #}
  {% set ns.MAIN_CORE_GOLD_FACT_TRANSACTIONS_UNIQUE_KEY = 'tx_hash' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'block_number' %}
  {% set ns.MAIN_CORE_GOLD_EZ_NATIVE_TRANSFERS_UNIQUE_KEY = 'tx_hash' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'block_number' %}
  {% set ns.MAIN_CORE_GOLD_EZ_NATIVE_TRANSFERS_PRICES_START_DATE = get_var('MAIN_CORE_GOLD_EZ_NATIVE_TRANSFERS_PRICES_START_DATE','2024-01-01') %}

  {% set ns.MAIN_CORE_GOLD_FACT_EVENT_LOGS_UNIQUE_KEY = 'tx_hash' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'block_number' %}

  {% set ns.MAIN_CORE_GOLD_TRACES_FULL_RELOAD_ENABLED = get_var('MAIN_CORE_GOLD_TRACES_FULL_RELOAD_ENABLED', false) %}
  {% set ns.MAIN_CORE_GOLD_TRACES_FR_MAX_BLOCK = get_var('MAIN_CORE_GOLD_TRACES_FR_MAX_BLOCK', 1000000) %}
  {% set ns.MAIN_CORE_GOLD_TRACES_FULL_RELOAD_BLOCKS_PER_RUN = get_var('MAIN_CORE_GOLD_TRACES_FULL_RELOAD_BLOCKS_PER_RUN', 1000000) %}
  {% set ns.MAIN_CORE_GOLD_TRACES_TX_STATUS_ENABLED = get_var('MAIN_CORE_GOLD_TRACES_TX_STATUS_ENABLED', false) %}
  {% set ns.MAIN_CORE_GOLD_TRACES_SCHEMA_NAME = get_var('MAIN_CORE_GOLD_TRACES_SCHEMA_NAME', 'silver') %}
  {% if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED %}
    {% if ns.MAIN_CORE_TRACES_SEI_MODE %}
        {% set ns.MAIN_CORE_GOLD_TRACES_UNIQUE_KEY = "concat(block_number, '-', tx_hash)" %}
    {% else %}
        {% set ns.MAIN_CORE_GOLD_TRACES_UNIQUE_KEY = "concat(block_number, '-', tx_position)" %}
    {% endif %}
  {% else %}
      {% set ns.MAIN_CORE_GOLD_TRACES_UNIQUE_KEY = "block_number" %}
  {% endif %}

  {# Main Streamline Variables #}
  {% set ns.MAIN_SL_BLOCKS_PER_HOUR = get_var('MAIN_SL_BLOCKS_PER_HOUR', 1) %}
  {% set ns.MAIN_SL_TRANSACTIONS_PER_BLOCK = get_var('MAIN_SL_TRANSACTIONS_PER_BLOCK', 1) %}
  {% set ns.MAIN_SL_TESTING_LIMIT = get_var('MAIN_SL_TESTING_LIMIT', none) %}
  {% set ns.MAIN_SL_NEW_BUILD_ENABLED = get_var('MAIN_SL_NEW_BUILD_ENABLED', false) %}
  {% set ns.MAIN_SL_CHAINHEAD_DELAY_MINUTES = get_var('MAIN_SL_CHAINHEAD_DELAY_MINUTES', 3) %}
  {% set ns.MAIN_SL_BLOCK_LOOKBACK_ENABLED = get_var('MAIN_SL_BLOCK_LOOKBACK_ENABLED', true) %}

  {# Main Test Variables #}
  {% set ns.MAIN_CORE_GOLD_TRACES_TEST_ERROR_THRESHOLD = get_var('MAIN_CORE_GOLD_TRACES_TEST_ERROR_THRESHOLD', 0) %}
  
  {# SL Blocks Transactions Variables #}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_SQL_LIMIT = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_SQL_LIMIT = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}
  
  {# SL Receipts Variables #}
  {% set ns.MAIN_SL_RECEIPTS_REALTIME_SQL_LIMIT = get_var('MAIN_SL_RECEIPTS_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_RECEIPTS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  
  {% set ns.MAIN_SL_RECEIPTS_HISTORY_SQL_LIMIT = get_var('MAIN_SL_RECEIPTS_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_RECEIPTS_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}
  
  {# SL Receipts By Hash Variables #}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_SQL_LIMIT = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_TXNS_MODEL_ENABLED = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_TXNS_MODEL_ENABLED', true) %}
  
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_HISTORY_SQL_LIMIT = get_var('MAIN_SL_RECEIPTS_BY_HASH_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_BY_HASH_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_BY_HASH_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_RECEIPTS_BY_HASH_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}
  
  {# SL Traces Variables #}
  {% set ns.MAIN_SL_TRACES_REALTIME_SQL_LIMIT = get_var('MAIN_SL_TRACES_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_TRACES_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_TRACES_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_TRACES_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  {% set ns.MAIN_SL_TRACES_REALTIME_REQUEST_START_BLOCK = get_var('MAIN_SL_TRACES_REALTIME_REQUEST_START_BLOCK', none) %}
  
  {% set ns.MAIN_SL_TRACES_HISTORY_SQL_LIMIT = get_var('MAIN_SL_TRACES_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_TRACES_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_TRACES_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_TRACES_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}
  {% set ns.MAIN_SL_TRACES_HISTORY_REQUEST_START_BLOCK = get_var('MAIN_SL_TRACES_HISTORY_REQUEST_START_BLOCK', none) %}
  
  {# SL Confirm Blocks Variables #}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_REALTIME_SQL_LIMIT = get_var('MAIN_SL_CONFIRM_BLOCKS_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_CONFIRM_BLOCKS_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_CONFIRM_BLOCKS_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_CONFIRM_BLOCKS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_HISTORY_SQL_LIMIT = get_var('MAIN_SL_CONFIRM_BLOCKS_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_CONFIRM_BLOCKS_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_CONFIRM_BLOCKS_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_CONFIRM_BLOCKS_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {# SL Decoder Variables #}
  {% set ns.DECODER_SL_TESTING_LIMIT = get_var('DECODER_SL_TESTING_LIMIT', none) %}
  {% set ns.DECODER_SL_NEW_BUILD_ENABLED = get_var('DECODER_SL_NEW_BUILD_ENABLED', false) %}

  {# SL Decoded Logs Variables #}
  {% set ns.DECODER_SL_DECODED_LOGS_REALTIME_EXTERNAL_TABLE = get_var('DECODER_SL_DECODED_LOGS_REALTIME_EXTERNAL_TABLE', 'decoded_logs') %}
  {% set ns.DECODER_SL_DECODED_LOGS_REALTIME_SQL_LIMIT = get_var('DECODER_SL_DECODED_LOGS_REALTIME_SQL_LIMIT', 10000000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_REALTIME_PRODUCER_BATCH_SIZE = get_var('DECODER_SL_DECODED_LOGS_REALTIME_PRODUCER_BATCH_SIZE', 5000000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_REALTIME_WORKER_BATCH_SIZE = get_var('DECODER_SL_DECODED_LOGS_REALTIME_WORKER_BATCH_SIZE', 50000) %}

  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_EXTERNAL_TABLE = get_var('DECODER_SL_DECODED_LOGS_HISTORY_EXTERNAL_TABLE', 'decoded_logs_history') %}
  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_SQL_LIMIT = get_var('DECODER_SL_DECODED_LOGS_HISTORY_SQL_LIMIT', 10000000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_PRODUCER_BATCH_SIZE = get_var('DECODER_SL_DECODED_LOGS_HISTORY_PRODUCER_BATCH_SIZE', 5000000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_WORKER_BATCH_SIZE = get_var('DECODER_SL_DECODED_LOGS_HISTORY_WORKER_BATCH_SIZE', 50000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_WAIT_SECONDS = get_var('DECODER_SL_DECODED_LOGS_HISTORY_WAIT_SECONDS', 60) %}

  {# SL Contract ABIs Variables #}
  {% set ns.DECODER_SL_CONTRACT_ABIS_REALTIME_SQL_LIMIT = get_var('DECODER_SL_CONTRACT_ABIS_REALTIME_SQL_LIMIT', 100) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_REALTIME_PRODUCER_BATCH_SIZE = get_var('DECODER_SL_CONTRACT_ABIS_REALTIME_PRODUCER_BATCH_SIZE', 1) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_REALTIME_WORKER_BATCH_SIZE = get_var('DECODER_SL_CONTRACT_ABIS_REALTIME_WORKER_BATCH_SIZE', 1) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('DECODER_SL_CONTRACT_ABIS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 1) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_INTERACTION_COUNT = get_var('DECODER_SL_CONTRACT_ABIS_INTERACTION_COUNT', 50) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_EXPLORER_URL = get_var('DECODER_SL_CONTRACT_ABIS_EXPLORER_URL', '') %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_EXPLORER_URL_SUFFIX = get_var('DECODER_SL_CONTRACT_ABIS_EXPLORER_URL_SUFFIX', '') %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_EXPLORER_VAULT_PATH = get_var('DECODER_SL_CONTRACT_ABIS_EXPLORER_VAULT_PATH', '') %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_BRONZE_TABLE_ENABLED = get_var('DECODER_SL_CONTRACT_ABIS_BRONZE_TABLE_ENABLED', false) %}

  {# ABIs Silver Variables #}
  {% set ns.DECODER_SILVER_CONTRACT_ABIS_EXPLORER_NAME = get_var('DECODER_SILVER_CONTRACT_ABIS_EXPLORER_NAME', '') %}
  {% set ns.DECODER_SILVER_CONTRACT_ABIS_ETHERSCAN_ENABLED = get_var('DECODER_SILVER_CONTRACT_ABIS_ETHERSCAN_ENABLED', false) %}
  {% set ns.DECODER_SILVER_CONTRACT_ABIS_RESULT_ENABLED = get_var('DECODER_SILVER_CONTRACT_ABIS_RESULT_ENABLED', false) %}

  {# SL Balances Variables #}
  {% set ns.BALANCES_SL_TESTING_LIMIT = get_var('BALANCES_SL_TESTING_LIMIT', none) %}
  {% set ns.BALANCES_SL_NEW_BUILD_ENABLED = get_var('BALANCES_SL_NEW_BUILD_ENABLED', false) %}
  {% set ns.BALANCES_SL_START_DATE = get_var('BALANCES_SL_START_DATE', '2025-06-10') %}
  {% set ns.BALANCES_SL_DAILY_REALTIME_LOOKBACK_DAYS = get_var('BALANCES_SL_DAILY_REALTIME_LOOKBACK_DAYS', -4) %}

  {% set ns.BALANCES_SL_ERC20_DAILY_REALTIME_SQL_LIMIT = get_var('BALANCES_SL_ERC20_DAILY_REALTIME_SQL_LIMIT', 12000000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_REALTIME_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_ERC20_DAILY_REALTIME_PRODUCER_BATCH_SIZE', 240000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_REALTIME_WORKER_BATCH_SIZE = get_var('BALANCES_SL_ERC20_DAILY_REALTIME_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_ERC20_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.BALANCES_SL_ERC20_DAILY_HISTORY_SQL_LIMIT = get_var('BALANCES_SL_ERC20_DAILY_HISTORY_SQL_LIMIT', 12000000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_HISTORY_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_ERC20_DAILY_HISTORY_PRODUCER_BATCH_SIZE', 600000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_HISTORY_WORKER_BATCH_SIZE = get_var('BALANCES_SL_ERC20_DAILY_HISTORY_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_ERC20_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.BALANCES_SL_NATIVE_DAILY_REALTIME_SQL_LIMIT = get_var('BALANCES_SL_NATIVE_DAILY_REALTIME_SQL_LIMIT', 12000000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_REALTIME_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_NATIVE_DAILY_REALTIME_PRODUCER_BATCH_SIZE', 240000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_REALTIME_WORKER_BATCH_SIZE = get_var('BALANCES_SL_NATIVE_DAILY_REALTIME_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_NATIVE_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.BALANCES_SL_NATIVE_DAILY_HISTORY_SQL_LIMIT = get_var('BALANCES_SL_NATIVE_DAILY_HISTORY_SQL_LIMIT', 12000000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_HISTORY_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_NATIVE_DAILY_HISTORY_PRODUCER_BATCH_SIZE', 600000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_HISTORY_WORKER_BATCH_SIZE = get_var('BALANCES_SL_NATIVE_DAILY_HISTORY_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_NATIVE_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.BALANCES_SL_STATE_TRACER_REALTIME_SQL_LIMIT = get_var('BALANCES_SL_STATE_TRACER_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_REALTIME_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_STATE_TRACER_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_REALTIME_WORKER_BATCH_SIZE = get_var('BALANCES_SL_STATE_TRACER_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_STATE_TRACER_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  
  {% set ns.BALANCES_SL_STATE_TRACER_HISTORY_SQL_LIMIT = get_var('BALANCES_SL_STATE_TRACER_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_HISTORY_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_STATE_TRACER_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_HISTORY_WORKER_BATCH_SIZE = get_var('BALANCES_SL_STATE_TRACER_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_STATE_TRACER_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {# Balances State Tracer Silver Variables #}
  {% set ns.BALANCES_EXCLUSION_LIST_ENABLED = get_var('BALANCES_EXCLUSION_LIST_ENABLED', false) %}
  {% set ns.BALANCES_VALIDATOR_CONTRACT_ADDRESS = get_var('BALANCES_VALIDATOR_CONTRACT_ADDRESS', '') %}
  {% set ns.BALANCES_SILVER_STATE_TRACER_FULL_RELOAD_ENABLED = get_var('BALANCES_SILVER_STATE_TRACER_FULL_RELOAD_ENABLED', false) %}
  {% set ns.BALANCES_SILVER_STATE_TRACER_FR_MAX_BLOCK = get_var('BALANCES_SILVER_STATE_TRACER_FR_MAX_BLOCK', 800000) %}
  {% set ns.BALANCES_SILVER_STATE_TRACER_FULL_RELOAD_BLOCKS_PER_RUN = get_var('BALANCES_SILVER_STATE_TRACER_FULL_RELOAD_BLOCKS_PER_RUN', 800000) %}

  {# SL Token Reads Variables #}
  {% set ns.MAIN_SL_TOKEN_READS_BRONZE_TABLE_ENABLED = get_var('MAIN_SL_TOKEN_READS_BRONZE_TABLE_ENABLED', false) %}
  {% set ns.MAIN_SL_TOKEN_READS_CONTRACT_LIMIT = get_var('MAIN_SL_TOKEN_READS_CONTRACT_LIMIT', 1000) %}
  {% set ns.MAIN_SL_TOKEN_READS_REALTIME_SQL_LIMIT = get_var('MAIN_SL_TOKEN_READS_REALTIME_SQL_LIMIT', 3000) %}
  {% set ns.MAIN_SL_TOKEN_READS_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_TOKEN_READS_REALTIME_PRODUCER_BATCH_SIZE', 1500) %}
  {% set ns.MAIN_SL_TOKEN_READS_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_TOKEN_READS_REALTIME_WORKER_BATCH_SIZE', 500) %}
  {% set ns.MAIN_SL_TOKEN_READS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_TOKEN_READS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 5) %}
  
  {# Observability Variables #}
  {% set ns.MAIN_OBSERV_FULL_TEST_ENABLED = get_var('MAIN_OBSERV_FULL_TEST_ENABLED', false) %}
  {% set ns.MAIN_OBSERV_EXCLUSION_LIST_ENABLED = get_var('MAIN_OBSERV_EXCLUSION_LIST_ENABLED', false) %}
  
  {# Prices Variables #}
  {% set ns.MAIN_PRICES_NATIVE_SYMBOLS = get_var('MAIN_PRICES_NATIVE_SYMBOLS', '') %}
  {% set ns.MAIN_PRICES_NATIVE_BLOCKCHAINS = get_var('MAIN_PRICES_NATIVE_BLOCKCHAINS', ns.GLOBAL_PROJECT_NAME.lower()) %}
  {% set ns.MAIN_PRICES_PROVIDER_PLATFORMS = get_var('MAIN_PRICES_PROVIDER_PLATFORMS', '') %}
  {% set ns.MAIN_PRICES_TOKEN_ADDRESSES = get_var('MAIN_PRICES_TOKEN_ADDRESSES', none) %}
  {% set ns.MAIN_PRICES_TOKEN_BLOCKCHAINS = get_var('MAIN_PRICES_TOKEN_BLOCKCHAINS', ns.GLOBAL_PROJECT_NAME.lower()) %}

  {# Labels Variables #}
  {% set ns.MAIN_LABELS_BLOCKCHAINS = get_var('MAIN_LABELS_BLOCKCHAINS', ns.GLOBAL_PROJECT_NAME.lower()) %}

  {# Scores Variables #}
  {% set ns.SCORES_FULL_RELOAD_ENABLED = get_var('SCORES_FULL_RELOAD_ENABLED', false) %}
  {% set ns.SCORES_LIMIT_DAYS = get_var('SCORES_LIMIT_DAYS', 30) %}
  
  {# NFT Variables #}

  {# Curated Variables #}
  {% set ns.CURATED_COMPLETE_LOOKBACK_HOURS = get_var('CURATED_COMPLETE_LOOKBACK_HOURS', '4 hours') %}
  {% set ns.CURATED_LOOKBACK_HOURS = get_var('CURATED_LOOKBACK_HOURS', '12 hours') %}
  {% set ns.CURATED_LOOKBACK_DAYS = get_var('CURATED_LOOKBACK_DAYS', '7 days') %}
  {% set ns.CURATED_START_TIMESTAMP = get_var('CURATED_START_TIMESTAMP', '2000-01-01 00:00:00') %}
  {% set ns.CURATED_FR_MODELS = get_var('CURATED_FR_MODELS', []) %}
  {% set ns.CURATED_DEFI_DEX_SWAPS_RECENCY_EXCLUSION_LIST = get_var('CURATED_DEFI_DEX_SWAPS_RECENCY_EXCLUSION_LIST', []) %}
  {% set ns.CURATED_DEFI_DEX_LP_ACTIONS_RECENCY_EXCLUSION_LIST = get_var('CURATED_DEFI_DEX_LP_ACTIONS_RECENCY_EXCLUSION_LIST', []) %}
  {% set ns.CURATED_DEFI_BRIDGE_RECENCY_EXCLUSION_LIST = get_var('CURATED_DEFI_BRIDGE_RECENCY_EXCLUSION_LIST', []) %}
  {% set ns.CURATED_DEFI_LENDING_RECENCY_EXCLUSION_LIST = get_var('CURATED_DEFI_LENDING_RECENCY_EXCLUSION_LIST', []) %}

  {# SL Contract Reads Variables #}
  {% set ns.CURATED_SL_CONTRACT_READS_DAILY_REALTIME_SQL_LIMIT = get_var('CURATED_SL_CONTRACT_READS_DAILY_REALTIME_SQL_LIMIT', 12000000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_DAILY_REALTIME_PRODUCER_BATCH_SIZE = get_var('CURATED_SL_CONTRACT_READS_DAILY_REALTIME_PRODUCER_BATCH_SIZE', 240000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_DAILY_REALTIME_WORKER_BATCH_SIZE = get_var('CURATED_SL_CONTRACT_READS_DAILY_REALTIME_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('CURATED_SL_CONTRACT_READS_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.CURATED_SL_CONTRACT_READS_DAILY_HISTORY_SQL_LIMIT = get_var('CURATED_SL_CONTRACT_READS_DAILY_HISTORY_SQL_LIMIT', 12000000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_DAILY_HISTORY_PRODUCER_BATCH_SIZE = get_var('CURATED_SL_CONTRACT_READS_DAILY_HISTORY_PRODUCER_BATCH_SIZE', 600000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_DAILY_HISTORY_WORKER_BATCH_SIZE = get_var('CURATED_SL_CONTRACT_READS_DAILY_HISTORY_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('CURATED_SL_CONTRACT_READS_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {# SL Stablecoin Reads Variables #}
  {% set ns.CURATED_SL_STABLECOIN_READS_REALTIME_SQL_LIMIT = get_var('CURATED_SL_STABLECOIN_READS_REALTIME_SQL_LIMIT', 3000) %}
  {% set ns.CURATED_SL_STABLECOIN_READS_REALTIME_PRODUCER_BATCH_SIZE = get_var('CURATED_SL_STABLECOIN_READS_REALTIME_PRODUCER_BATCH_SIZE', 1500) %}
  {% set ns.CURATED_SL_STABLECOIN_READS_REALTIME_WORKER_BATCH_SIZE = get_var('CURATED_SL_STABLECOIN_READS_REALTIME_WORKER_BATCH_SIZE', 500) %}
  {% set ns.CURATED_SL_STABLECOIN_READS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('CURATED_SL_STABLECOIN_READS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 5) %}

  {% set ns.CURATED_SL_STABLECOIN_READS_HISTORY_SQL_LIMIT = get_var('CURATED_SL_STABLECOIN_READS_HISTORY_SQL_LIMIT', 20000) %}
  {% set ns.CURATED_SL_STABLECOIN_READS_HISTORY_PRODUCER_BATCH_SIZE = get_var('CURATED_SL_STABLECOIN_READS_HISTORY_PRODUCER_BATCH_SIZE', 1500) %}
  {% set ns.CURATED_SL_STABLECOIN_READS_HISTORY_WORKER_BATCH_SIZE = get_var('CURATED_SL_STABLECOIN_READS_HISTORY_WORKER_BATCH_SIZE', 500) %}
  {% set ns.CURATED_SL_STABLECOIN_READS_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('CURATED_SL_STABLECOIN_READS_HISTORY_ASYNC_CONCURRENT_REQUESTS', 5) %}

  {# Curated Bridge Variables #}
  {% set ns.CURATED_DEFI_BRIDGE_CONTRACT_MAPPING = get_var('CURATED_DEFI_BRIDGE_CONTRACT_MAPPING', {}) %}
  {% set ns.CURATED_DEFI_BRIDGE_ALLBRIDGE_SOURCE_CHAIN = get_var('CURATED_DEFI_BRIDGE_ALLBRIDGE_SOURCE_CHAIN', '') %}
  {% set ns.CURATED_DEFI_BRIDGE_HOP_L1_CONTRACTS = get_var('CURATED_DEFI_BRIDGE_HOP_L1_CONTRACTS', []) %}
  {% set ns.CURATED_DEFI_BRIDGE_HOP_BRIDGE_CONTRACT = get_var('CURATED_DEFI_BRIDGE_HOP_BRIDGE_CONTRACT', '') %}
  {% set ns.CURATED_DEFI_BRIDGE_HOP_TOKEN_CONTRACT = get_var('CURATED_DEFI_BRIDGE_HOP_TOKEN_CONTRACT', '') %}

  {# Curated DEX Variables #}
  {% set ns.CURATED_DEFI_DEX_SWAPS_CONTRACT_MAPPING = get_var('CURATED_DEFI_DEX_SWAPS_CONTRACT_MAPPING', {}) %}
  {% set ns.CURATED_DEFI_DEX_DEXALOT_DEST_CHAIN_ID = get_var('CURATED_DEFI_DEX_DEXALOT_DEST_CHAIN_ID', 0) %}

  {# Curated Lending Variables #}
  {% set ns.CURATED_DEFI_LENDING_CONTRACT_MAPPING = get_var('CURATED_DEFI_LENDING_CONTRACT_MAPPING', {}) %}
  
  {# Return the entire namespace as a dictionary #}
  {{ return(ns) }}
{% endmacro %}