{% macro return_vars() %}
  {# This macro sets and returns all configurable variables used throughout the project,
     organizing them by category (Global, Bronze, Silver, Streamline, Decoder etc.) with default values.
     IMPORTANT: Only call get_var() once per variable #}
  
  {# Set all variables on the namespace #}
  {% set ns = namespace() %}
  
  {# Set Variables and Default Values, organized by category #}
  
  {# Global Variables #}
  {% set ns.GLOBAL_PROJECT_NAME = get_var('GLOBAL_PROJECT_NAME', '') %}
  {% set ns.GLOBAL_NODE_PROVIDER = get_var('GLOBAL_NODE_PROVIDER', '') %}
  {% set ns.GLOBAL_NODE_URL = get_var('GLOBAL_NODE_URL', '{Service}/{Authentication}') %}
  {% set ns.GLOBAL_NATIVE_ASSET_SYMBOL = get_var('GLOBAL_NATIVE_ASSET_SYMBOL', '') %}
  {% set ns.GLOBAL_WRAPPED_NATIVE_ASSET_ADDRESS = get_var('GLOBAL_WRAPPED_NATIVE_ASSET_ADDRESS', '') %}
  {% set ns.GLOBAL_WRAPPED_NATIVE_ASSET_SYMBOL = get_var('GLOBAL_WRAPPED_NATIVE_ASSET_SYMBOL', '') %}
  {% set ns.GLOBAL_MAX_SEQUENCE_NUMBER = get_var('GLOBAL_MAX_SEQUENCE_NUMBER', 1000000000) %}
  {% set ns.GLOBAL_NODE_VAULT_PATH = get_var('GLOBAL_NODE_VAULT_PATH', '') %}
  {% set ns.GLOBAL_NETWORK = get_var('GLOBAL_NETWORK', 'mainnet') %}
  {% set ns.GLOBAL_START_BLOCK = get_var('GLOBAL_START_BLOCK', 0) %}
  {% set ns.GLOBAL_ALT_NODE_ENABLED = get_var('GLOBAL_ALT_NODE_ENABLED', false) %}
  {% set ns.GLOBAL_ALT_NODE_VAULT_PATH = get_var('GLOBAL_ALT_NODE_VAULT_PATH', '') %}

  {% set ns.GLOBAL_BRONZE_FR_ENABLED = none if get_var('GLOBAL_BRONZE_FR_ENABLED', false) else false %} {# Sets to none if true, still requires --full-refresh, otherwise will use incremental #}
  {% set ns.GLOBAL_SILVER_FR_ENABLED = none if get_var('GLOBAL_SILVER_FR_ENABLED', false) else false %} 
  {% set ns.GLOBAL_GOLD_FR_ENABLED = none if get_var('GLOBAL_GOLD_FR_ENABLED', false) else false %} 
  {% set ns.GLOBAL_STREAMLINE_FR_ENABLED = none if get_var('GLOBAL_STREAMLINE_FR_ENABLED', false) else false %} 
  {% set ns.GLOBAL_NEW_BUILD_ENABLED = get_var('GLOBAL_NEW_BUILD_ENABLED', false) %}

  {% set ns.GLOBAL_CHANGE_TRACKING_ENABLED = get_var('GLOBAL_CHANGE_TRACKING_ENABLED', false) %}
  
  {# Main GHA Workflow Variables #}
  {% set ns.MAIN_GHA_STREAMLINE_CHAINHEAD_CRON = get_var('MAIN_GHA_STREAMLINE_CHAINHEAD_CRON', '0,30 * * * *') %}
  {% set ns.MAIN_GHA_SCHEDULED_MAIN_CRON = get_var('MAIN_GHA_SCHEDULED_MAIN_CRON', none) %}
  {% set ns.MAIN_GHA_SCHEDULED_CURATED_CRON = get_var('MAIN_GHA_SCHEDULED_CURATED_CRON', none) %}
  {% set ns.MAIN_GHA_SCHEDULED_ABIS_CRON = get_var('MAIN_GHA_SCHEDULED_ABIS_CRON', none) %}
  {% set ns.MAIN_GHA_SCHEDULED_SCORES_CRON = get_var('MAIN_GHA_SCHEDULED_SCORES_CRON', none) %}
  {% set ns.MAIN_GHA_TEST_DAILY_CRON = get_var('MAIN_GHA_TEST_DAILY_CRON', none) %}
  {% set ns.MAIN_GHA_TEST_INTRADAY_CRON = get_var('MAIN_GHA_TEST_INTRADAY_CRON', none) %}
  {% set ns.MAIN_GHA_TEST_MONTHLY_CRON = get_var('MAIN_GHA_TEST_MONTHLY_CRON', none) %}
  {% set ns.MAIN_GHA_HEAL_MODELS_CRON = get_var('MAIN_GHA_HEAL_MODELS_CRON', none) %}
  {% set ns.MAIN_GHA_FULL_OBSERVABILITY_CRON = get_var('MAIN_GHA_FULL_OBSERVABILITY_CRON', none) %}
  {% set ns.MAIN_GHA_DEV_REFRESH_CRON = get_var('MAIN_GHA_DEV_REFRESH_CRON', none) %}
  {% set ns.MAIN_GHA_STREAMLINE_DECODER_HISTORY_CRON = get_var('MAIN_GHA_STREAMLINE_DECODER_HISTORY_CRON', none) %}

  {# Custom GHA Workflow Variables #}
  {% set ns.CUSTOM_GHA_STREAMLINE_DEXALOT_CHAINHEAD_CRON = get_var('CUSTOM_GHA_STREAMLINE_DEXALOT_CHAINHEAD_CRON', none) %}
  {% set ns.CUSTOM_GHA_SCHEDULED_DEXALOT_MAIN_CRON = get_var('CUSTOM_GHA_SCHEDULED_DEXALOT_MAIN_CRON', none) %}
  {% set ns.CUSTOM_GHA_TEST_BEACON_CRON = get_var('CUSTOM_GHA_TEST_BEACON_CRON', none) %}
  {% set ns.CUSTOM_GHA_STREAMLINE_READS_CRON = get_var('CUSTOM_GHA_STREAMLINE_READS_CRON', none) %}
  {% set ns.CUSTOM_GHA_STREAMLINE_BEACON_CRON = get_var('CUSTOM_GHA_STREAMLINE_BEACON_CRON', none) %}
  {% set ns.CUSTOM_GHA_SCHEDULED_BEACON_CRON = get_var('CUSTOM_GHA_SCHEDULED_BEACON_CRON', none) %}
  {% set ns.CUSTOM_GHA_NFT_READS_CRON = get_var('CUSTOM_GHA_NFT_READS_CRON', none) %}
  {% set ns.CUSTOM_GHA_NFT_LIST_CRON = get_var('CUSTOM_GHA_NFT_LIST_CRON', none) %}

  {# Core Variables #}
  {% set ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED = get_var('MAIN_CORE_RECEIPTS_BY_HASH_ENABLED', false) %}

  {% set ns.MAIN_CORE_TRACES_ARB_MODE = ns.GLOBAL_PROJECT_NAME.upper() == 'ARBITRUM' %}
  {% set ns.MAIN_CORE_TRACES_SEI_MODE = ns.GLOBAL_PROJECT_NAME.upper() == 'SEI' %}
  {% set ns.MAIN_CORE_TRACES_KAIA_MODE = ns.GLOBAL_PROJECT_NAME.upper() == 'KAIA' %}

  {# Core Bronze Variables #}
  {% set ns.MAIN_CORE_BRONZE_BLOCKS_ERROR_CODE_ENABLED = get_var('MAIN_CORE_BRONZE_BLOCKS_ERROR_CODE_ENABLED', false) %}
  {% set ns.MAIN_CORE_BRONZE_TOKEN_READS_LIMIT = get_var('MAIN_CORE_BRONZE_TOKEN_READS_LIMIT', 50) %}
  {% set ns.MAIN_CORE_BRONZE_TOKEN_READS_BATCHED_ENABLED = get_var('MAIN_CORE_BRONZE_TOKEN_READS_BATCHED_ENABLED', false) %}

  {# Core Silver Variables #}
  {% set ns.MAIN_CORE_SILVER_RECEIPTS_UNIQUE_KEY = 'tx_hash' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'block_number' %}
  {% set ns.MAIN_CORE_SILVER_RECEIPTS_SOURCE_NAME = 'RECEIPTS_BY_HASH' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'RECEIPTS' %}
  {% set ns.MAIN_CORE_SILVER_RECEIPTS_POST_HOOK = "ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION on equality(tx_hash, block_number)" if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else "ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION on equality(array_index, block_number)" %}

  {% set ns.MAIN_CORE_SILVER_CONFIRM_BLOCKS_FULL_RELOAD_ENABLED = get_var('MAIN_CORE_SILVER_CONFIRM_BLOCKS_FULL_RELOAD_ENABLED', false) %}

  {% set ns.MAIN_CORE_SILVER_TRACES_FULL_RELOAD_ENABLED = get_var('MAIN_CORE_SILVER_TRACES_FULL_RELOAD_ENABLED', false) %}
  {% set ns.MAIN_CORE_SILVER_TRACES_FR_MAX_BLOCK = get_var('MAIN_CORE_SILVER_TRACES_FR_MAX_BLOCK', 1000000) %}
  {% set ns.MAIN_CORE_SILVER_TRACES_FULL_RELOAD_BLOCKS_PER_RUN = get_var('MAIN_CORE_SILVER_TRACES_FULL_RELOAD_BLOCKS_PER_RUN', 1000000) %}
  {% set ns.MAIN_CORE_SILVER_TRACES_PARTITION_KEY_ENABLED = get_var('MAIN_CORE_SILVER_TRACES_PARTITION_KEY_ENABLED', true) %}

  {# Core Gold Variables #}
  {% set ns.MAIN_CORE_GOLD_FACT_TRANSACTIONS_UNIQUE_KEY = 'tx_hash' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'block_number' %}
  {% set ns.MAIN_CORE_GOLD_EZ_NATIVE_TRANSFERS_UNIQUE_KEY = 'tx_hash' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'block_number' %}
  {% set ns.MAIN_CORE_GOLD_EZ_NATIVE_TRANSFERS_PRICES_START_DATE = get_var('MAIN_CORE_GOLD_EZ_NATIVE_TRANSFERS_PRICES_START_DATE','2024-01-01') %}

  {% set ns.MAIN_CORE_GOLD_FACT_EVENT_LOGS_UNIQUE_KEY = 'tx_hash' if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED else 'block_number' %}

  {% set ns.MAIN_CORE_GOLD_TRACES_FULL_RELOAD_ENABLED = get_var('MAIN_CORE_GOLD_TRACES_FULL_RELOAD_ENABLED', false) %}
  {% set ns.MAIN_CORE_GOLD_TRACES_FR_MAX_BLOCK = get_var('MAIN_CORE_GOLD_TRACES_FR_MAX_BLOCK', 1000000) %}
  {% set ns.MAIN_CORE_GOLD_TRACES_FULL_RELOAD_BLOCKS_PER_RUN = get_var('MAIN_CORE_GOLD_TRACES_FULL_RELOAD_BLOCKS_PER_RUN', 1000000) %}
  {% set ns.MAIN_CORE_GOLD_TRACES_TX_STATUS_ENABLED = get_var('MAIN_CORE_GOLD_TRACES_TX_STATUS_ENABLED', false) %}
  {% set ns.MAIN_CORE_GOLD_TRACES_SCHEMA_NAME = get_var('MAIN_CORE_GOLD_TRACES_SCHEMA_NAME', 'silver') %}
  {% if ns.MAIN_CORE_RECEIPTS_BY_HASH_ENABLED %}
    {% if ns.MAIN_CORE_TRACES_SEI_MODE %}
        {% set ns.MAIN_CORE_GOLD_TRACES_UNIQUE_KEY = "concat(block_number, '-', tx_hash)" %}
    {% else %}
        {% set ns.MAIN_CORE_GOLD_TRACES_UNIQUE_KEY = "concat(block_number, '-', tx_position)" %}
    {% endif %}
  {% else %}
      {% set ns.MAIN_CORE_GOLD_TRACES_UNIQUE_KEY = "block_number" %}
  {% endif %}

  {# Main Streamline Variables #}
  {% set ns.MAIN_SL_BLOCKS_PER_HOUR = get_var('MAIN_SL_BLOCKS_PER_HOUR', 1) %}
  {% set ns.MAIN_SL_TRANSACTIONS_PER_BLOCK = get_var('MAIN_SL_TRANSACTIONS_PER_BLOCK', 1) %}
  {% set ns.MAIN_SL_TESTING_LIMIT = get_var('MAIN_SL_TESTING_LIMIT', none) %}
  {% set ns.MAIN_SL_NEW_BUILD_ENABLED = get_var('MAIN_SL_NEW_BUILD_ENABLED', false) %}
  {% set ns.MAIN_SL_CHAINHEAD_DELAY_MINUTES = get_var('MAIN_SL_CHAINHEAD_DELAY_MINUTES', 3) %}
  {% set ns.MAIN_SL_BLOCK_LOOKBACK_ENABLED = get_var('MAIN_SL_BLOCK_LOOKBACK_ENABLED', true) %}

  {# Main Test Variables #}
  {% set ns.MAIN_CORE_GOLD_TRACES_TEST_ERROR_THRESHOLD = get_var('MAIN_CORE_GOLD_TRACES_TEST_ERROR_THRESHOLD', 0) %}
  
  {# SL Blocks Transactions Variables #}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_SQL_LIMIT = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_SQL_LIMIT = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_BLOCKS_TRANSACTIONS_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}
  
  {# SL Receipts Variables #}
  {% set ns.MAIN_SL_RECEIPTS_REALTIME_SQL_LIMIT = get_var('MAIN_SL_RECEIPTS_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_RECEIPTS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  
  {% set ns.MAIN_SL_RECEIPTS_HISTORY_SQL_LIMIT = get_var('MAIN_SL_RECEIPTS_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_RECEIPTS_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_RECEIPTS_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}
  
  {# SL Receipts By Hash Variables #}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_SQL_LIMIT = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_REALTIME_TXNS_MODEL_ENABLED = get_var('MAIN_SL_RECEIPTS_BY_HASH_REALTIME_TXNS_MODEL_ENABLED', true) %}
  
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_HISTORY_SQL_LIMIT = get_var('MAIN_SL_RECEIPTS_BY_HASH_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_BY_HASH_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_RECEIPTS_BY_HASH_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR * ns.MAIN_SL_TRANSACTIONS_PER_BLOCK) %}
  {% set ns.MAIN_SL_RECEIPTS_BY_HASH_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_RECEIPTS_BY_HASH_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}
  
  {# SL Traces Variables #}
  {% set ns.MAIN_SL_TRACES_REALTIME_SQL_LIMIT = get_var('MAIN_SL_TRACES_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_TRACES_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_TRACES_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_TRACES_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  {% set ns.MAIN_SL_TRACES_REALTIME_REQUEST_START_BLOCK = get_var('MAIN_SL_TRACES_REALTIME_REQUEST_START_BLOCK', none) %}
  
  {% set ns.MAIN_SL_TRACES_HISTORY_SQL_LIMIT = get_var('MAIN_SL_TRACES_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_TRACES_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_TRACES_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_TRACES_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_TRACES_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}
  {% set ns.MAIN_SL_TRACES_HISTORY_REQUEST_START_BLOCK = get_var('MAIN_SL_TRACES_HISTORY_REQUEST_START_BLOCK', none) %}
  
  {# SL Confirm Blocks Variables #}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_REALTIME_SQL_LIMIT = get_var('MAIN_SL_CONFIRM_BLOCKS_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_CONFIRM_BLOCKS_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_CONFIRM_BLOCKS_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_CONFIRM_BLOCKS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_HISTORY_SQL_LIMIT = get_var('MAIN_SL_CONFIRM_BLOCKS_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_HISTORY_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_CONFIRM_BLOCKS_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_HISTORY_WORKER_BATCH_SIZE = get_var('MAIN_SL_CONFIRM_BLOCKS_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.MAIN_SL_CONFIRM_BLOCKS_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_CONFIRM_BLOCKS_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {# SL Decoder Variables #}
  {% set ns.DECODER_SL_TESTING_LIMIT = get_var('DECODER_SL_TESTING_LIMIT', none) %}
  {% set ns.DECODER_SL_NEW_BUILD_ENABLED = get_var('DECODER_SL_NEW_BUILD_ENABLED', false) %}

  {# SL Decoded Logs Variables #}
  {% set ns.DECODER_SL_DECODED_LOGS_REALTIME_EXTERNAL_TABLE = get_var('DECODER_SL_DECODED_LOGS_REALTIME_EXTERNAL_TABLE', 'decoded_logs') %}
  {% set ns.DECODER_SL_DECODED_LOGS_REALTIME_SQL_LIMIT = get_var('DECODER_SL_DECODED_LOGS_REALTIME_SQL_LIMIT', 10000000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_REALTIME_PRODUCER_BATCH_SIZE = get_var('DECODER_SL_DECODED_LOGS_REALTIME_PRODUCER_BATCH_SIZE', 5000000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_REALTIME_WORKER_BATCH_SIZE = get_var('DECODER_SL_DECODED_LOGS_REALTIME_WORKER_BATCH_SIZE', 50000) %}

  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_EXTERNAL_TABLE = get_var('DECODER_SL_DECODED_LOGS_HISTORY_EXTERNAL_TABLE', 'decoded_logs_history') %}
  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_SQL_LIMIT = get_var('DECODER_SL_DECODED_LOGS_HISTORY_SQL_LIMIT', 10000000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_PRODUCER_BATCH_SIZE = get_var('DECODER_SL_DECODED_LOGS_HISTORY_PRODUCER_BATCH_SIZE', 5000000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_WORKER_BATCH_SIZE = get_var('DECODER_SL_DECODED_LOGS_HISTORY_WORKER_BATCH_SIZE', 50000) %}
  {% set ns.DECODER_SL_DECODED_LOGS_HISTORY_WAIT_SECONDS = get_var('DECODER_SL_DECODED_LOGS_HISTORY_WAIT_SECONDS', 60) %}

  {# SL Contract ABIs Variables #}
  {% set ns.DECODER_SL_CONTRACT_ABIS_REALTIME_SQL_LIMIT = get_var('DECODER_SL_CONTRACT_ABIS_REALTIME_SQL_LIMIT', 100) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_REALTIME_PRODUCER_BATCH_SIZE = get_var('DECODER_SL_CONTRACT_ABIS_REALTIME_PRODUCER_BATCH_SIZE', 1) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_REALTIME_WORKER_BATCH_SIZE = get_var('DECODER_SL_CONTRACT_ABIS_REALTIME_WORKER_BATCH_SIZE', 1) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('DECODER_SL_CONTRACT_ABIS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 1) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_INTERACTION_COUNT = get_var('DECODER_SL_CONTRACT_ABIS_INTERACTION_COUNT', 50) %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_EXPLORER_URL = get_var('DECODER_SL_CONTRACT_ABIS_EXPLORER_URL', '') %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_EXPLORER_URL_SUFFIX = get_var('DECODER_SL_CONTRACT_ABIS_EXPLORER_URL_SUFFIX', '') %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_EXPLORER_VAULT_PATH = get_var('DECODER_SL_CONTRACT_ABIS_EXPLORER_VAULT_PATH', '') %}
  {% set ns.DECODER_SL_CONTRACT_ABIS_BRONZE_TABLE_ENABLED = get_var('DECODER_SL_CONTRACT_ABIS_BRONZE_TABLE_ENABLED', false) %}

  {# ABIs Silver Variables #}
  {% set ns.DECODER_SILVER_CONTRACT_ABIS_EXPLORER_NAME = get_var('DECODER_SILVER_CONTRACT_ABIS_EXPLORER_NAME', '') %}
  {% set ns.DECODER_SILVER_CONTRACT_ABIS_ETHERSCAN_ENABLED = get_var('DECODER_SILVER_CONTRACT_ABIS_ETHERSCAN_ENABLED', false) %}
  {% set ns.DECODER_SILVER_CONTRACT_ABIS_RESULT_ENABLED = get_var('DECODER_SILVER_CONTRACT_ABIS_RESULT_ENABLED', false) %}

  {# SL Balances Variables #}
  {% set ns.BALANCES_SL_TESTING_LIMIT = get_var('BALANCES_SL_TESTING_LIMIT', none) %}
  {% set ns.BALANCES_SL_NEW_BUILD_ENABLED = get_var('BALANCES_SL_NEW_BUILD_ENABLED', false) %}
  {% set ns.BALANCES_SL_START_DATE = get_var('BALANCES_SL_START_DATE', '2025-06-10') %}
  {% set ns.BALANCES_SL_DAILY_REALTIME_LOOKBACK_DAYS = get_var('BALANCES_SL_DAILY_REALTIME_LOOKBACK_DAYS', -4) %}

  {% set ns.BALANCES_SL_ERC20_DAILY_REALTIME_SQL_LIMIT = get_var('BALANCES_SL_ERC20_DAILY_REALTIME_SQL_LIMIT', 12000000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_REALTIME_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_ERC20_DAILY_REALTIME_PRODUCER_BATCH_SIZE', 240000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_REALTIME_WORKER_BATCH_SIZE = get_var('BALANCES_SL_ERC20_DAILY_REALTIME_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_ERC20_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.BALANCES_SL_ERC20_DAILY_HISTORY_SQL_LIMIT = get_var('BALANCES_SL_ERC20_DAILY_HISTORY_SQL_LIMIT', 12000000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_HISTORY_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_ERC20_DAILY_HISTORY_PRODUCER_BATCH_SIZE', 600000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_HISTORY_WORKER_BATCH_SIZE = get_var('BALANCES_SL_ERC20_DAILY_HISTORY_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.BALANCES_SL_ERC20_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_ERC20_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.BALANCES_SL_NATIVE_DAILY_REALTIME_SQL_LIMIT = get_var('BALANCES_SL_NATIVE_DAILY_REALTIME_SQL_LIMIT', 12000000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_REALTIME_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_NATIVE_DAILY_REALTIME_PRODUCER_BATCH_SIZE', 240000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_REALTIME_WORKER_BATCH_SIZE = get_var('BALANCES_SL_NATIVE_DAILY_REALTIME_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_NATIVE_DAILY_REALTIME_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.BALANCES_SL_NATIVE_DAILY_HISTORY_SQL_LIMIT = get_var('BALANCES_SL_NATIVE_DAILY_HISTORY_SQL_LIMIT', 12000000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_HISTORY_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_NATIVE_DAILY_HISTORY_PRODUCER_BATCH_SIZE', 600000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_HISTORY_WORKER_BATCH_SIZE = get_var('BALANCES_SL_NATIVE_DAILY_HISTORY_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.BALANCES_SL_NATIVE_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_NATIVE_DAILY_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.BALANCES_SL_STATE_TRACER_REALTIME_SQL_LIMIT = get_var('BALANCES_SL_STATE_TRACER_REALTIME_SQL_LIMIT', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_REALTIME_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_STATE_TRACER_REALTIME_PRODUCER_BATCH_SIZE', 2 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_REALTIME_WORKER_BATCH_SIZE = get_var('BALANCES_SL_STATE_TRACER_REALTIME_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_STATE_TRACER_REALTIME_ASYNC_CONCURRENT_REQUESTS', 100) %}
  
  {% set ns.BALANCES_SL_STATE_TRACER_HISTORY_SQL_LIMIT = get_var('BALANCES_SL_STATE_TRACER_HISTORY_SQL_LIMIT', 1000 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_HISTORY_PRODUCER_BATCH_SIZE = get_var('BALANCES_SL_STATE_TRACER_HISTORY_PRODUCER_BATCH_SIZE', 10 * ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_HISTORY_WORKER_BATCH_SIZE = get_var('BALANCES_SL_STATE_TRACER_HISTORY_WORKER_BATCH_SIZE', ns.MAIN_SL_BLOCKS_PER_HOUR) %}
  {% set ns.BALANCES_SL_STATE_TRACER_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('BALANCES_SL_STATE_TRACER_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {# Balances State Tracer Silver Variables #}
  {% set ns.BALANCES_EXCLUSION_LIST_ENABLED = get_var('BALANCES_EXCLUSION_LIST_ENABLED', false) %}
  {% set ns.BALANCES_VALIDATOR_CONTRACT_ADDRESS = get_var('BALANCES_VALIDATOR_CONTRACT_ADDRESS', '') %}
  {% set ns.BALANCES_SILVER_STATE_TRACER_FULL_RELOAD_ENABLED = get_var('BALANCES_SILVER_STATE_TRACER_FULL_RELOAD_ENABLED', false) %}
  {% set ns.BALANCES_SILVER_STATE_TRACER_FR_MAX_BLOCK = get_var('BALANCES_SILVER_STATE_TRACER_FR_MAX_BLOCK', 800000) %}
  {% set ns.BALANCES_SILVER_STATE_TRACER_FULL_RELOAD_BLOCKS_PER_RUN = get_var('BALANCES_SILVER_STATE_TRACER_FULL_RELOAD_BLOCKS_PER_RUN', 800000) %}

  {# SL Token Reads Variables #}
  {% set ns.MAIN_SL_TOKEN_READS_BRONZE_TABLE_ENABLED = get_var('MAIN_SL_TOKEN_READS_BRONZE_TABLE_ENABLED', false) %}
  {% set ns.MAIN_SL_TOKEN_READS_CONTRACT_LIMIT = get_var('MAIN_SL_TOKEN_READS_CONTRACT_LIMIT', 1000) %}
  {% set ns.MAIN_SL_TOKEN_READS_REALTIME_SQL_LIMIT = get_var('MAIN_SL_TOKEN_READS_REALTIME_SQL_LIMIT', 3000) %}
  {% set ns.MAIN_SL_TOKEN_READS_REALTIME_PRODUCER_BATCH_SIZE = get_var('MAIN_SL_TOKEN_READS_REALTIME_PRODUCER_BATCH_SIZE', 1500) %}
  {% set ns.MAIN_SL_TOKEN_READS_REALTIME_WORKER_BATCH_SIZE = get_var('MAIN_SL_TOKEN_READS_REALTIME_WORKER_BATCH_SIZE', 500) %}
  {% set ns.MAIN_SL_TOKEN_READS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('MAIN_SL_TOKEN_READS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 5) %}
  
  {# Observability Variables #}
  {% set ns.MAIN_OBSERV_FULL_TEST_ENABLED = get_var('MAIN_OBSERV_FULL_TEST_ENABLED', false) %}
  {% set ns.MAIN_OBSERV_EXCLUSION_LIST_ENABLED = get_var('MAIN_OBSERV_EXCLUSION_LIST_ENABLED', false) %}
  
  {# Prices Variables #}
  {% set ns.MAIN_PRICES_NATIVE_SYMBOLS = get_var('MAIN_PRICES_NATIVE_SYMBOLS', '') %}
  {% set ns.MAIN_PRICES_NATIVE_BLOCKCHAINS = get_var('MAIN_PRICES_NATIVE_BLOCKCHAINS', ns.GLOBAL_PROJECT_NAME.lower()) %}
  {% set ns.MAIN_PRICES_PROVIDER_PLATFORMS = get_var('MAIN_PRICES_PROVIDER_PLATFORMS', '') %}
  {% set ns.MAIN_PRICES_TOKEN_ADDRESSES = get_var('MAIN_PRICES_TOKEN_ADDRESSES', none) %}
  {% set ns.MAIN_PRICES_TOKEN_BLOCKCHAINS = get_var('MAIN_PRICES_TOKEN_BLOCKCHAINS', ns.GLOBAL_PROJECT_NAME.lower()) %}

  {# Labels Variables #}
  {% set ns.MAIN_LABELS_BLOCKCHAINS = get_var('MAIN_LABELS_BLOCKCHAINS', ns.GLOBAL_PROJECT_NAME.lower()) %}

  {# Scores Variables #}
  {% set ns.SCORES_FULL_RELOAD_ENABLED = get_var('SCORES_FULL_RELOAD_ENABLED', false) %}
  {% set ns.SCORES_LIMIT_DAYS = get_var('SCORES_LIMIT_DAYS', 30) %}
  
  {# NFT Variables #}

  {# Curated Variables #}
  {% set ns.CURATED_COMPLETE_LOOKBACK_HOURS = get_var('CURATED_COMPLETE_LOOKBACK_HOURS', '4 hours') %}
  {% set ns.CURATED_LOOKBACK_HOURS = get_var('CURATED_LOOKBACK_HOURS', '12 hours') %}
  {% set ns.CURATED_LOOKBACK_DAYS = get_var('CURATED_LOOKBACK_DAYS', '7 days') %}
  {% set ns.CURATED_START_TIMESTAMP = get_var('CURATED_START_TIMESTAMP', '2000-01-01 00:00:00') %}
  {% set ns.CURATED_FR_MODELS = get_var('CURATED_FR_MODELS', []) %}
  {% set ns.CURATED_DEFI_DEX_SWAPS_RECENCY_EXCLUSION_LIST = get_var('CURATED_DEFI_DEX_SWAPS_RECENCY_EXCLUSION_LIST', []) %}
  {% set ns.CURATED_DEFI_DEX_LP_ACTIONS_RECENCY_EXCLUSION_LIST = get_var('CURATED_DEFI_DEX_LP_ACTIONS_RECENCY_EXCLUSION_LIST', []) %}
  {% set ns.CURATED_DEFI_BRIDGE_RECENCY_EXCLUSION_LIST = get_var('CURATED_DEFI_BRIDGE_RECENCY_EXCLUSION_LIST', []) %}
  {% set ns.CURATED_DEFI_LENDING_RECENCY_EXCLUSION_LIST = get_var('CURATED_DEFI_LENDING_RECENCY_EXCLUSION_LIST', []) %}

  {# SL Contract Reads Variables #}
  {% set ns.CURATED_SL_CONTRACT_READS_START_DATE = get_var('CURATED_SL_CONTRACT_READS_START_DATE', '2025-06-10') %}

  {% set ns.CURATED_SL_CONTRACT_READS_REALTIME_SQL_LIMIT = get_var('CURATED_SL_CONTRACT_READS_REALTIME_SQL_LIMIT', 12000000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_REALTIME_PRODUCER_BATCH_SIZE = get_var('CURATED_SL_CONTRACT_READS_REALTIME_PRODUCER_BATCH_SIZE', 240000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_REALTIME_WORKER_BATCH_SIZE = get_var('CURATED_SL_CONTRACT_READS_REALTIME_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_REALTIME_ASYNC_CONCURRENT_REQUESTS = get_var('CURATED_SL_CONTRACT_READS_REALTIME_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {% set ns.CURATED_SL_CONTRACT_READS_HISTORY_SQL_LIMIT = get_var('CURATED_SL_CONTRACT_READS_HISTORY_SQL_LIMIT', 12000000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_HISTORY_PRODUCER_BATCH_SIZE = get_var('CURATED_SL_CONTRACT_READS_HISTORY_PRODUCER_BATCH_SIZE', 600000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_HISTORY_WORKER_BATCH_SIZE = get_var('CURATED_SL_CONTRACT_READS_HISTORY_WORKER_BATCH_SIZE', 60000) %}
  {% set ns.CURATED_SL_CONTRACT_READS_HISTORY_ASYNC_CONCURRENT_REQUESTS = get_var('CURATED_SL_CONTRACT_READS_HISTORY_ASYNC_CONCURRENT_REQUESTS', 10) %}

  {# Protocol Variables - Protocol-specific contract addresses for curated models #}
  {# AAVE #}
  {% set ns.PROTOCOL_AAVE_TOKEN_ADDRESS = get_var('PROTOCOL_AAVE_TOKEN_ADDRESS', '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9') %}
  {% set ns.PROTOCOL_AAVE_ECOSYSTEM_RESERVE = get_var('PROTOCOL_AAVE_ECOSYSTEM_RESERVE', '0x25f2226b597e8f9514b3f68f00f494cf4f286491') %}
  {% set ns.PROTOCOL_AAVE_SAFETY_MODULE_STKAAVE = get_var('PROTOCOL_AAVE_SAFETY_MODULE_STKAAVE', '0x4da27a545c0c5b758a6ba100e3a049001de870f5') %}
  {% set ns.PROTOCOL_AAVE_SAFETY_MODULE_STKABPT = get_var('PROTOCOL_AAVE_SAFETY_MODULE_STKABPT', '0xa1116930326d21fb917d5a27f1e9943a9595fb47') %}
  {% set ns.PROTOCOL_AAVE_SAFETY_MODULE_STKGHO = get_var('PROTOCOL_AAVE_SAFETY_MODULE_STKGHO', '0x1a88df1cfe15af22b3c4c783d4e6f7f9e0c1885d') %}
  {% set ns.PROTOCOL_AAVE_COLLECTOR_V2 = get_var('PROTOCOL_AAVE_COLLECTOR_V2', '0x464c71f6c2f760dda6093dcb91c24c39e5d6e18c') %}
  {% set ns.PROTOCOL_AAVE_AAVURA_TREASURY = get_var('PROTOCOL_AAVE_AAVURA_TREASURY', '0x89c51828427f70d77875c6747759fb17ba10ceb0') %}
  {% set ns.PROTOCOL_AAVE_V3_POOL = get_var('PROTOCOL_AAVE_V3_POOL', '') %}
  {% set ns.PROTOCOL_AAVE_V2_POOL = get_var('PROTOCOL_AAVE_V2_POOL', '') %}
  {% set ns.PROTOCOL_AAVE_GHO_TOKEN = get_var('PROTOCOL_AAVE_GHO_TOKEN', '0x40d16fc0246ad3160ccc09b8d0d3a2cd28ae6c2f') %}
  {% set ns.PROTOCOL_AAVE_GHO_TREASURY = get_var('PROTOCOL_AAVE_GHO_TREASURY', '0x00907f9921424583e7ffbfedf84f92b7b2be4977') %}
  {% set ns.PROTOCOL_AAVE_INCENTIVES_CONTROLLER = get_var('PROTOCOL_AAVE_INCENTIVES_CONTROLLER', '') %}
  {% set ns.PROTOCOL_AAVE_INCENTIVES_CONTROLLER_V3 = get_var('PROTOCOL_AAVE_INCENTIVES_CONTROLLER_V3', '') %}
  {% set ns.PROTOCOL_AAVE_COLLECTOR = get_var('PROTOCOL_AAVE_COLLECTOR', '') %}
  {% set ns.PROTOCOL_AAVE_BALANCER_POOL = get_var('PROTOCOL_AAVE_BALANCER_POOL', '0xc697051d1c6296c24ae3bcef39aca743861d9a81') %}

  {# LIDO #}
  {% set ns.PROTOCOL_LIDO_STETH_ADDRESS = get_var('PROTOCOL_LIDO_STETH_ADDRESS', '0xae7ab96520de3a18e5e111b5eaab095312d7fe84') %}
  {% set ns.PROTOCOL_LIDO_LDO_TOKEN = get_var('PROTOCOL_LIDO_LDO_TOKEN', '0x5a98fcbea516cf06857215779fd812ca3bef1b32') %}
  {% set ns.PROTOCOL_LIDO_TREASURY = get_var('PROTOCOL_LIDO_TREASURY', '0x3e40d73eb977dc6a537af587d48316fee66e9c8c') %}
  {% set ns.PROTOCOL_LIDO_NODE_OPERATORS_REGISTRY = get_var('PROTOCOL_LIDO_NODE_OPERATORS_REGISTRY', '0x55032650b14df07b85bf18a3a3ec8e0af2e028d5') %}

  {# EIGENLAYER #}
  {% set ns.PROTOCOL_EIGENLAYER_POD_MANAGER = get_var('PROTOCOL_EIGENLAYER_POD_MANAGER', '0x91e677b07f7af907ec9a428aafa9fc14a0d3a338') %}
  {% set ns.PROTOCOL_EIGENLAYER_DELEGATION_MANAGER = get_var('PROTOCOL_EIGENLAYER_DELEGATION_MANAGER', '0x39053d51b77dc0d36036fc1fcc8cb819df8ef37a') %}
  {% set ns.PROTOCOL_EIGENLAYER_STRATEGY_MANAGER = get_var('PROTOCOL_EIGENLAYER_STRATEGY_MANAGER', '0x858646372cc42e1a627fce94aa7a7033e7cf075a') %}
  {% set ns.PROTOCOL_EIGENLAYER_REWARDS_COORDINATOR = get_var('PROTOCOL_EIGENLAYER_REWARDS_COORDINATOR', '0x7750d328b314effa365a0402ccfd489b80b0add7') %}

  {# UNISWAP #}
  {% set ns.PROTOCOL_UNISWAP_UNI_TOKEN = get_var('PROTOCOL_UNISWAP_UNI_TOKEN', '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984') %}
  {% set ns.PROTOCOL_UNISWAP_TREASURY = get_var('PROTOCOL_UNISWAP_TREASURY', '0x1a9c8182c09f50c8318d769245bea52c32be35bc') %}
  {% set ns.PROTOCOL_UNISWAP_GOVERNANCE_TIMELOCK = get_var('PROTOCOL_UNISWAP_GOVERNANCE_TIMELOCK', '0x1a9c8182c09f50c8318d769245bea52c32be35bc') %}

  {# MAKER #}
  {% set ns.PROTOCOL_MAKER_DAI_TOKEN = get_var('PROTOCOL_MAKER_DAI_TOKEN', '0x6b175474e89094c44da98b954eedeac495271d0f') %}
  {% set ns.PROTOCOL_MAKER_MKR_TOKEN = get_var('PROTOCOL_MAKER_MKR_TOKEN', '0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2') %}
  {% set ns.PROTOCOL_MAKER_VOW = get_var('PROTOCOL_MAKER_VOW', '0xa950524441892a31ebddf91d3ceefa04bf454466') %}
  {% set ns.PROTOCOL_MAKER_VAT = get_var('PROTOCOL_MAKER_VAT', '0x35d1b3f3d7966a1dfe207aa4514c12a259a0492b') %}
  {% set ns.PROTOCOL_MAKER_JUG = get_var('PROTOCOL_MAKER_JUG', '0x19c0976f590d67707e62397c87829d896dc0f1f1') %}
  {% set ns.PROTOCOL_MAKER_POT = get_var('PROTOCOL_MAKER_POT', '0x197e90f9fad81970ba7976f33cbd77088e5d7cf7') %}
  {% set ns.PROTOCOL_MAKER_PAUSE_PROXY = get_var('PROTOCOL_MAKER_PAUSE_PROXY', '0xbe8e3e3618f7474f8cb1d074a26affef007e98fb') %}

  {# BALANCER #}
  {% set ns.PROTOCOL_BALANCER_BAL_TOKEN = get_var('PROTOCOL_BALANCER_BAL_TOKEN', '0xba100000625a3754423978a60c9317c58a424e3d') %}
  {% set ns.PROTOCOL_BALANCER_VAULT_V2 = get_var('PROTOCOL_BALANCER_VAULT_V2', '0xba12222222228d8ba445958a75a0704d566bf2c8') %}
  {% set ns.PROTOCOL_BALANCER_TREASURY = get_var('PROTOCOL_BALANCER_TREASURY', '0x10a19e7ee7d7f8a52822f6817de8ea18204f2e4f') %}

  {# CHAINLINK #}
  {% set ns.PROTOCOL_CHAINLINK_LINK_TOKEN = get_var('PROTOCOL_CHAINLINK_LINK_TOKEN', '0x514910771af9ca656af840dff83e8264ecf986ca') %}
  {% set ns.PROTOCOL_CHAINLINK_STAKING_V02 = get_var('PROTOCOL_CHAINLINK_STAKING_V02', '0xbc10f2e862ed4502f71ef8c2e5f94fbe0c699a5d') %}

  {# CONVEX #}
  {% set ns.PROTOCOL_CONVEX_CVX_TOKEN = get_var('PROTOCOL_CONVEX_CVX_TOKEN', '0x4e3fbd56cd56c3e72c1403e103b45db9da5b9d2b') %}
  {% set ns.PROTOCOL_CONVEX_BOOSTER = get_var('PROTOCOL_CONVEX_BOOSTER', '0xf403c135812408bfbe8713b5a23a04b3d48aae31') %}
  {% set ns.PROTOCOL_CONVEX_CVX_REWARD_POOL = get_var('PROTOCOL_CONVEX_CVX_REWARD_POOL', '0xcf50b810e57ac33b91dcf525c6ddd9881b139332') %}

  {# LIQUITY #}
  {% set ns.PROTOCOL_LIQUITY_LUSD_TOKEN = get_var('PROTOCOL_LIQUITY_LUSD_TOKEN', '0x5f98805a4e8be255a32880fdec7f6728c6568ba0') %}
  {% set ns.PROTOCOL_LIQUITY_LQTY_TOKEN = get_var('PROTOCOL_LIQUITY_LQTY_TOKEN', '0x6dea81c8171d0ba574754ef6f8b412f2ed88c54d') %}
  {% set ns.PROTOCOL_LIQUITY_STABILITY_POOL = get_var('PROTOCOL_LIQUITY_STABILITY_POOL', '0x66017d22b0f8556afdd19fc67041899eb65a21bb') %}
  {% set ns.PROTOCOL_LIQUITY_TROVE_MANAGER = get_var('PROTOCOL_LIQUITY_TROVE_MANAGER', '0xa39739ef8b0231dbfa0dcda07d7e29faabcf4bb2') %}

  {# GOLDFINCH #}
  {% set ns.PROTOCOL_GOLDFINCH_GFI_TOKEN = get_var('PROTOCOL_GOLDFINCH_GFI_TOKEN', '0xdab396ccf3d84cf2d07c4454e10c8a6f5b008d2b') %}
  {% set ns.PROTOCOL_GOLDFINCH_SENIOR_POOL = get_var('PROTOCOL_GOLDFINCH_SENIOR_POOL', '0x8481a6ebaf5c7dabc3f7e09e44a89531fd31f822') %}
  {% set ns.PROTOCOL_GOLDFINCH_CREDIT_DESK = get_var('PROTOCOL_GOLDFINCH_CREDIT_DESK', '0x3249508e4c5c22c0f2ea3d23b33122c11268ef76') %}

  {# RENZO #}
  {% set ns.PROTOCOL_RENZO_EZETH_TOKEN = get_var('PROTOCOL_RENZO_EZETH_TOKEN', '0xbf5495efe5db9ce00f80364c8b423567e58d2110') %}
  {% set ns.PROTOCOL_RENZO_RESTAKE_MANAGER = get_var('PROTOCOL_RENZO_RESTAKE_MANAGER', '0x74a09653a083691711cf8215a6ab074bb4e99ef5') %}

  {# AERODROME (Base) #}
  {% set ns.PROTOCOL_AERODROME_AERO_TOKEN = get_var('PROTOCOL_AERODROME_AERO_TOKEN', '0x940181a94a35a4569e4529a3cdfb74e38fd98631') %}
  {% set ns.PROTOCOL_AERODROME_ROUTER_V2 = get_var('PROTOCOL_AERODROME_ROUTER_V2', '0xcf77a3ba9a5ca399b7c97c74d54e5b1beb874e43') %}
  {% set ns.PROTOCOL_AERODROME_VOTER = get_var('PROTOCOL_AERODROME_VOTER', '0x16613524e02ad97edfef371bc883f2f5d6c480a5') %}

  {# Common Tokens #}
  {% set ns.TOKEN_WETH = get_var('TOKEN_WETH', '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2') %}
  {% set ns.TOKEN_WBTC = get_var('TOKEN_WBTC', '0x2260fac5e5542a773aa44fbcfedf7c193bc2c599') %}
  {% set ns.TOKEN_USDC = get_var('TOKEN_USDC', '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48') %}
  {% set ns.TOKEN_USDT = get_var('TOKEN_USDT', '0xdac17f958d2ee523a2206206994597c13d831ec7') %}
  {% set ns.TOKEN_DAI = get_var('TOKEN_DAI', '0x6b175474e89094c44da98b954eedeac495271d0f') %}
  {% set ns.TOKEN_WSTETH = get_var('TOKEN_WSTETH', '0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0') %}
  {% set ns.TOKEN_RETH = get_var('TOKEN_RETH', '0xae78736cd615f374d3085123a210448e74fc6393') %}
  {% set ns.TOKEN_CBETH = get_var('TOKEN_CBETH', '0xbe9895146f7af43049ca1c1ae358b0541ea49704') %}

  {# Curated Bridge Variables #}
  {% set ns.CURATED_DEFI_BRIDGE_CONTRACT_MAPPING = get_var('CURATED_DEFI_BRIDGE_CONTRACT_MAPPING', {}) %}
  {% set ns.CURATED_DEFI_BRIDGE_ALLBRIDGE_SOURCE_CHAIN = get_var('CURATED_DEFI_BRIDGE_ALLBRIDGE_SOURCE_CHAIN', '') %}
  {% set ns.CURATED_DEFI_BRIDGE_HOP_L1_CONTRACTS = get_var('CURATED_DEFI_BRIDGE_HOP_L1_CONTRACTS', []) %}
  {% set ns.CURATED_DEFI_BRIDGE_HOP_BRIDGE_CONTRACT = get_var('CURATED_DEFI_BRIDGE_HOP_BRIDGE_CONTRACT', '') %}
  {% set ns.CURATED_DEFI_BRIDGE_HOP_TOKEN_CONTRACT = get_var('CURATED_DEFI_BRIDGE_HOP_TOKEN_CONTRACT', '') %}

  {# Curated DEX Variables #}
  {% set ns.CURATED_DEFI_DEX_SWAPS_CONTRACT_MAPPING = get_var('CURATED_DEFI_DEX_SWAPS_CONTRACT_MAPPING', {}) %}
  {% set ns.CURATED_DEFI_DEX_DEXALOT_DEST_CHAIN_ID = get_var('CURATED_DEFI_DEX_DEXALOT_DEST_CHAIN_ID', 0) %}

  {# Curated Lending Variables #}
  {% set ns.CURATED_DEFI_LENDING_CONTRACT_MAPPING = get_var('CURATED_DEFI_LENDING_CONTRACT_MAPPING', {}) %}
  
  {# Return the entire namespace as a dictionary #}
  {{ return(ns) }}
{% endmacro %}