name: dbt_run_template_alter_all_gha_tasks

on:
  workflow_call:
    inputs:
      task_action:
        type: string
        description: 'Action to perform on all tasks (RESUME, SUSPEND)'
        required: true
        default: RESUME
      target:
        type: string
        required: false
        default: prod

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment:
      name: workflow_secrets

    steps:
      - uses: actions/checkout@v3
      
      - name: Extract project & profile names from dbt_project.yml
        id: project-name
        run: |
          PROFILE_NAME=$(grep "^profile:" dbt_project.yml | sed 's/^profile:[[:space:]]*"//' | sed 's/".*$//')
          PROJECT_NAME=$(grep "^name:" dbt_project.yml | sed 's/^name:[[:space:]]*"//' | sed 's/".*$//')
          echo "PROFILE_NAME=$PROFILE_NAME" >> $GITHUB_ENV
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "PROFILE_NAME: $PROFILE_NAME"
          echo "PROJECT_NAME: $PROJECT_NAME"
      
      - name: Set environment variables
        run: |
          echo "TARGET=${{ inputs.target }}" >> $GITHUB_ENV
          echo "ACCOUNT=vna27887.us-east-1" >> $GITHUB_ENV
          echo "REGION=us-east-1" >> $GITHUB_ENV
          echo "SCHEMA=ADMIN" >> $GITHUB_ENV
          echo "USER=DBT_CLOUD_$PROFILE_NAME" >> $GITHUB_ENV  
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
          
          if [[ "${{ inputs.target }}" == *"prod"* ]]; then
            echo "DATABASE=$PROFILE_NAME" >> $GITHUB_ENV
            echo "ROLE=DBT_CLOUD_$PROFILE_NAME" >> $GITHUB_ENV
            echo "WAREHOUSE=DBT_CLOUD" >> $GITHUB_ENV
          elif [[ "${{ inputs.target }}" == *"test"* ]]; then
            echo "DATABASE=$PROFILE_NAME" >> $GITHUB_ENV
            echo "ROLE=DBT_CLOUD_$PROFILE_NAME" >> $GITHUB_ENV
            echo "WAREHOUSE=DBT_TEST" >> $GITHUB_ENV
          else
            echo "DATABASE=${PROFILE_NAME}_DEV" >> $GITHUB_ENV
            echo "ROLE=INTERNAL_DEV" >> $GITHUB_ENV
            echo "WAREHOUSE=DBT_CLOUD" >> $GITHUB_ENV
          fi
          
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          dbt deps
      
      - name: Generate task names from existing workflows
        run: |
          TASK_NAMES=""
          for file in $(find .github/workflows -name "*.yml" -type f); do
            filename=$(basename "$file" .yml)
            task="TRIGGER_$(echo $filename | tr '[:lower:]' '[:upper:]')"
            if [ -z "$TASK_NAMES" ]; then
              TASK_NAMES="$task"
            else
              TASK_NAMES="$TASK_NAMES,$task"
            fi
          done
          echo "TASK_NAMES=$TASK_NAMES" >> $GITHUB_ENV
          echo "Found task names: $TASK_NAMES"

      - name: Run DBT Jobs
        run: |
          if [ -n "$TASK_NAMES" ]; then
            dbt run-operation fsc_evm.alter_gha_tasks --args '{"task_names": "${{ env.TASK_NAMES }}", "task_action": "${{ inputs.task_action }}"}' 
          else
            echo "No workflow files found. No tasks to alter."
          fi

  notify-failure:
    needs: [run_dbt_jobs]
    if: failure()
    uses: ./.github/workflows/slack_notify.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}