name: Update fsc-evm Version Across Repos

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New fsc-evm version tag (e.g., v4.5.4)'
        required: true
        type: string
      projects:
        description: 'Comma-separated github_repo names or "all" (default: all)'
        required: false
        type: string
        default: 'all'

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test
        run: |
          echo "Version: ${{ inputs.version }}"
          echo "Projects: ${{ inputs.projects }}"
          echo "This is a test"