version: 2 

sources:
  - name: github_actions
    database: "{{ target.database }}"
    schema: github_actions
    tables:
      - name: workflows
  - name: bronze_streamline
    database: streamline
    schema: >-
      {{ target.database.upper() ~ ('_DEV' if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", false) else '') }}
    tables:
      - name: blocks
      - name: blocks_v2
      - name: transactions
      - name: transactions_v2
      - name: receipts_by_hash
      - name: receipts
      - name: receipts_v2
      - name: traces
      - name: traces_v2
      - name: debug_traceblockbynumber
      - name: confirm_blocks
      - name: confirm_blocks_v2
      - name: decoded_logs
      - name: decoded_logs_v2
      - name: decoded_traces
      - name: decoded_traces_v2
      - name: contract_abis
      - name: contract_abis_v2
      - name: eth_balances
      - name: eth_balances_v2
      - name: token_balances
      - name: token_balances_v2
      - name: beacon_blocks
      - name: beacon_blocks_v2
      - name: beacon_validators
      - name: beacon_validators_v2
      - name: reads
      - name: reads_v2
  - name: crosschain_silver
    database: >-
      {{ 'CROSSCHAIN_DEV' if '_DEV' in target.database.upper() else 'CROSSCHAIN' }}
    schema: silver
    tables:
      - name: labels_combined
      - name: complete_provider_asset_metadata
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: complete_provider_prices
      - name: complete_token_asset_metadata
      - name: complete_token_prices
  - name: bronze_api
    database: "{{ target.database }}"
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: silver
    database: "{{ target.database }}"
    schema: silver
    tables:
      - name: verified_abis
  - name: data_science_silver
    database: datascience
    schema: silver
    tables:
      - name: evm_event_sigs
      - name: evm_known_event_names
      - name: evm_known_event_sigs
      - name: evm_wrapped_assets
      - name: dates
      - name: scoring_activity_categories
  - name: fsc_evm_admin
    database: >-
      {{ 'FSC_EVM_DEV' if '_DEV' in target.database.upper() else 'FSC_EVM' }}
    schema: admin
    tables:
      - name: _master_keys