version: 2

macros:
  - name: init_config
    description: >
      Initializes the configuration system for the current DBT project.
      This macro runs a Python script to process configuration files 
      and generate a JSON cache that is used by other macros.
      It should be called once at the beginning of the DBT run
      via the on-run-start hook.
    docs:
      show: true
    arguments: []

  - name: get_config
    description: >
      Retrieves a configuration value by key. This is the primary way
      to access chain-specific configuration values in DBT models.
      The values are retrieved from a pre-processed JSON cache.
    docs:
      show: true
    arguments:
      - name: key
        type: string
        description: The configuration key to retrieve
      - name: default
        type: any
        description: The default value to return if key not found
        default: ''

  - name: get_children
    description: >
      Retrieves all child configuration values for a parent key.
      This is useful for hierarchical configurations like token mappings.
      The values are retrieved from a pre-processed JSON cache.
    docs:
      show: true
    arguments:
      - name: parent_key
        type: string
        description: The parent configuration key